baseURL = "https://aws-saa-learning.pages.dev/"   # thay bằng domain Cloudflare Pages
languageCode = "en-us"
title = "My LMS Hugo"
theme = ""  # nếu dùng theme ngoài thì điền tên ở đây

# cho phép tạo JSON output cho questions
[outputs]
  section = ["HTML", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
